# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

			- name: Fetch Github Release Asset
				# You may pin to the exact commit or the version.
				# uses: dsaltares/fetch-gh-release-asset@aa37ae5c44d3c9820bc12fe675e8670ecd93bd1c
				uses: dsaltares/fetch-gh-release-asset@0.0.5
				with:
					# org/repo to download from
					repo: # optional, default is 
					# version of the release to download from
					version: # optional, default is latest
					# name of the file in the release to download
					file: 
					# optional Personal Access Token to access external repository
					token: # optional, default is 
