name: Push to another repo

on:
  workflow_dispatch

jobs:
  publish_latest_release_to_package_server:
    name: Push latest release to another repo
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_SSH_KEY }}"
          
      - name: Clone another repo
        uses: actions/checkout@v2
        with: 
          repository: "git@github.com:CodeCrafter912/AnotherTest.git"
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          path: "."
          
      - name: Prepare download
        run: mkdir "packages"
          
      - name: Download assets from latest release
        uses: Itsblue/download-release-assets-action@v4
        with:
          file: ".*"
          path: "./packages"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout test-branch
          git add *
          git commit -a -m "test (By GitHub actions)"
          git push
        
