on:
  workflow_dispatch

name: Build and Upload Release Asset

jobs:
  build:
    name: Build and Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build stuff lol
        run: ./build.sh

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: archives
          path: archives
  
  create-release:
    name: Build and Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         name: archives
          
     - name: Display structure of downloaded files
       run: ls -R
