on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build and Upload Release Asset

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build stuff lol
        run: ./build.sh

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: test
  
  process:
    name: Process
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: test
          path: test
    
      - name: Display structure of downloaded files
        run: ls -R

  publish-release:
    needs: process
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    name: GitHub Release
